# Conclusion

This report mainly focuses on the scores, grades and types of violations and explores the relationship between cuisine type and violations, cuisine types and scores, as well as the violation types for the most popular franchises. According to the graphs drawn and the analysis made, the grades of restaurants have little to do with the boroughs, since each grade has almost the same distribution in each borough. From the results of the initial inspection and the re-inspection, we know that restaurants of type fast food and franchise are more likely to have higher grades for the initial inspection. From the time and scores analysis for each cuisine type, we notice that the scores don't change a lot for most of the cuisine types as time goes by and stays between 10 and 20. According to the franchise analysis, all franchises tend to have the "non-food contract surface inappropariate" problem and other sanitation problems also take large proportions. 

We hope this report provides a general idea of how cuisine types and locations are related to grades, scores and violations, as well as the possible reasons behind. In this report, we only divide the violation types into two groups. However, there are more than two types of inspections with more detailed descriptions. There might be more information gained using all types for future analysis. We treat all cuisine types separately in this report. However, it might be useful to combine some cuisine types into a larger group to make the graph more clear and there might be more trends detected if doing this way.